### ISSUE TITLE
Broken websocket in recent tTRPC versions

### ISSUE THREAD

**Issue by rmn-nknv** [cah4a/trpc-bun-adapter#16]
Websocket subscriptions do not work with @trpc/server versions from 11.0.0-rc.748 to 11.0.0-rc.808. They work on 11.0.0-rc.747.
There are no problems with simple HTTP.

Logs
@trpc/server 11.0.0-rc.808
trpc-bun-adapter 1.2.22
bun 1.1.43

```
{
  error: 62 |     constructor(opts){
63 |         const cause = getCauseFromUnknown(opts.cause);
64 |         const message = opts.message ?? cause?.message ?? opts.code;
65 |         // eslint-disable-next-line @typescript-eslint/ban-ts-comment
66 |         // @ts-ignore https://github.com/tc39/proposal-error-cause
67 |         super(message, {
             ^
TRPCError: import_server.callProcedure is not a function. (In 'import_server.callProcedure({
          procedures: router._def.procedures,
          path,
          getRawInput: () => Promise.resolve(input),
          ctx,
          type,
          signal: abortController.signal
        })', 'import_server.callProcedure' is undefined)
  code: "INTERNAL_SERVER_ERROR",

      at [masked]/node_modules/.pnpm/@trpc+server@11.0.0-rc.808_typescript@5.7.3/node_modules/@trpc/server/dist/unstable-core-do-not-import/error/TRPCError.js:67:9

129 |           message: `Duplicate id ${id}`,
130 |           code: "BAD_REQUEST"
131 |         });
132 |       }
133 |       const abortController = new AbortController();
134 |       const result = await (0, import_server.callProcedure)({
                                                   ^
TypeError: import_server.callProcedure is not a function. (In 'import_server.callProcedure({
          procedures: router._def.procedures,
          path,
          getRawInput: () => Promise.resolve(input),
          ctx,
          type,
          signal: abortController.signal
        })', 'import_server.callProcedure' is undefined)
      at [masked]/node_modules/.pnpm/trpc-bun-adapter@1.2.2_@trpc+server@11.0.0-rc.808_typescript@5.7.3_/node_modules/trpc-bun-adapter/dist/index.js:134:46
,
  path: "...",
  type: "subscription",
  ctx: {},
  req: Request (0 KB) {
    method: "GET",
    url: "http://localhost:3000/api/trpc",
    headers: Headers {}
  },
  input: {
    [masked]
  },
}
```

Thank you for your code.

**Comment by cah4a** [comment]
Hey @rmn-nknv,

Thanks so much for your contribution and patience!

I've updated the package to support tRPC v11.0.0 (stable).
You can now enjoy it in version v1.3.0.
